############################################################
#
# 文章静态化微服务
# web访问端口号  约定：8001
#
############################################################
server:
  #  port: 8003
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: prod   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: service-article-html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #  mongodb
  data:
    mongodb:
      uri: mongodb://admin:123456@124.222.219.104:27017
      database: imooc-news
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
#    settings:
#      classic_compatible: true
  rabbitmq:
    host: 124.222.219.104
    username: admin
    password: admin
    port: 5672
#    不同开发环境
    virtual-host: news


# 定义freemarker生成的html位置
freemarker:
  html:
    target: /Users/xiaokaixin/Desktop/imooc-news/myftl
    article: /usr/local/apache-tomcat-9.0.46/webapps/imooc-news/portal/a

############################################################
#
# eureka配置信息
#
############################################################
eureka:
  # 自定义eureka server的信息
  server:
    hostname: eureka
    port: 9000
  client:
    # 所有的微服务都必须注册到eureka中
    register-with-eureka: true
    # 从注册中心获得检索服务实例
    fetch-registry: true
    # 注册中心的服务地址
    service-url:
      #      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      defaultZone: http://eureka-cluster-9001:9001/eureka/,http://eureka-cluster-9002:9002/eureka/,http://eureka-cluster-9003:9003/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3      # 调整微服务（eureka client）和注册中心（eureka server）的心跳时间
    lease-expiration-duration-in-seconds: 5   # eureka 举例最近的一次心跳等待提出的时间，默认90s
